# Generated by Django 6.0 on 2026-05-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MIMICRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('record_id', models.CharField(max_length=50)),
                ('diretorio', models.CharField(max_length=300)),
                ('frequencia_amostragem', models.FloatField(default=125)),
                ('possui_ecg', models.BooleanField(default=True)),
                ('possui_abp', models.BooleanField(default=True)),
                ('possui_ppg', models.BooleanField(default=True)),
                ('possui_resp', models.BooleanField(default=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
