# Generated by Django 6.0 on 2026-05-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAVsimulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mimicrecord',
            name='arquivo_dat',
            field=models.FileField(blank=True, null=True, upload_to='dav/datasets/dat/'),
        ),
        migrations.AddField(
            model_name='mimicrecord',
            name='arquivo_hea',
            field=models.FileField(blank=True, null=True, upload_to='dav/datasets/hea/'),
        ),
        migrations.AddField(
            model_name='mimicrecord',
            name='arquivo_numerics_dat',
            field=models.FileField(blank=True, null=True, upload_to='dav/datasets/numerics_dat/'),
        ),
        migrations.AddField(
            model_name='mimicrecord',
            name='arquivo_numerics_hea',
            field=models.FileField(blank=True, null=True, upload_to='dav/datasets/numerics_hea/'),
        ),
        migrations.AlterField(
            model_name='mimicrecord',
            name='diretorio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='mimicrecord',
            name='record_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
