# Generated by Django 6.0 on 2026-05-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAVsimulator', '0002_mimicrecord_arquivo_dat_mimicrecord_arquivo_hea_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mimicrecord',
            name='arquivo_zip',
            field=models.FileField(blank=True, null=True, upload_to='dav/datasets/zip/'),
        ),
    ]
