# Generated by Django 6.0 on 2026-05-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DAVsimulator', '0003_mimicrecord_arquivo_zip'),
    ]

    operations = [
        migrations.AddField(
            model_name='mimicrecord',
            name='pasta_extraida',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
